package entities;

// Generated May 26, 2015 1:52:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name = "card", catalog = "atm")
public class Card implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String cardNo;
	private Customer customer;
	private String pin;
	private String balance;
	private Set<Log> logs = new HashSet<Log>(0);

	public Card() {
	}
	
	public Card(Card c) {
		this.cardNo = c.cardNo;
		this.customer = c.customer;
		this.pin = c.pin;
		this.balance = c.balance;
		this.logs = c.logs;
	}

	public Card(String cardNo, Customer customer, String pin, String balance) {
		this.cardNo = cardNo;
		this.customer = customer;
		this.pin = pin;
		this.balance = balance;
	}

	public Card(String cardNo, Customer customer, String pin, String balance,
			Set<Log> logs) {
		this.cardNo = cardNo;
		this.customer = customer;
		this.pin = pin;
		this.balance = balance;
		this.logs = logs;
	}

	@Id
	@Column(name = "CardNo", unique = true, nullable = false, length = 10)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustID", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "PIN", nullable = false, length = 32)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "Balance", nullable = false, length = 16777215)
	public String getBalance() {
		return this.balance;
	}

	public void setBalance(String balance) {
		this.balance = balance;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "card")
	public Set<Log> getLogs() {
		return this.logs;
	}

	public void setLogs(Set<Log> logs) {
		this.logs = logs;
	}
}
